apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foster.fullname" . }}
  labels:
    app: {{ include "foster.name" . }}
    chart: {{ include "foster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.fosterSecretKey }}
  foster-secret-key:  {{ .Values.fosterSecretKey | b64enc | quote }}
  {{ else }}
  foster-secret-key: {{ randAlphaNum 60 | b64enc | quote }}
  {{ end }}
  postgres-password: {{ required ".Values.postgres.password is required!" .Values.postgres.password | b64enc | quote }}
